export const SUCCESS = 'SUCCESS';
export const FAILURE = 'FAILURE';
export const SOURCE_PATH_INPUT_CHANGE = 'SOURCE_PATH_INPUT_CHANGE';
export const SOURCE_PATH_INPUT_SUBMIT = 'SOURCE_PATH_INPUT_SUBMIT';
export const OUTPUT_PATH_INPUT_CHANGE = 'OUTPUT_PATH_INPUT_CHANGE';
export const OUTPUT_PATH_INPUT_SUBMIT = 'OUTPUT_PATH_INPUT_SUBMIT';
export const HTML_MIN_CHANGE = 'HTML_MIN_CHANGE';
